>>> import py_cuffs
>>> py_cuffs.start()

Spectral points per block  : 42
Threads per block          : 1024
Spectral points per thread : 0

Init v : 
Loading v0.npy...
Done!
Loading da.npy...
Done!

Init wL: 
Loading log_2gs.npy...
Done!
Loading na.npy...
Done!
Initializing Lorentzian parameters  (from cache)... 
Done!

Init wG: 
Loading log_2vMm.npy...
Done!
Initializing Gaussian parameters (from cache)... 
Done!

Init I: 
Loading S0.npy...
Done!
Loading El.npy...
Done!

Number of lines loaded: 55581120

Allocating device memory...
Done!
Copying data to device... 
Done!
Press any key to start iterations...

checkpoint -1...
checkpoint 0...
checkpoint 0.1...
checkpoint 0.2...
checkpoint 0.3...
checkpoint 1...
checkpoint 1.1...
checkpoint 1.2...
checkpoint 1.3...
checkpoint 1.4...
checkpoint 1.5...
checkpoint 1.6...
checkpoint 1.7...
checkpoint 1.8...
checkpoint 1.9...
checkpoint 1.10...
checkpoint 1.11...
checkpoint 2...
Getting ready...
checkpoint 3...
checkpoint 4...
<<<LAUNCHED>>> 
Traceback (most recent call last):
  File "cupy/cuda/runtime.pyx", line 270, in cupy.cuda.runtime.deviceSynchronize
  File "cupy/cuda/runtime.pyx", line 273, in cupy.cuda.runtime.deviceSynchronize
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Exception ignored in: 'py_cuffs.iterate'
Traceback (most recent call last):
  File "cupy/cuda/runtime.pyx", line 270, in cupy.cuda.runtime.deviceSynchronize
  File "cupy/cuda/runtime.pyx", line 273, in cupy.cuda.runtime.deviceSynchronize
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered

